//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> StatesId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string EmployeeProfile { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> HomeNumber { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Status { get; set; }
    
        public virtual City City { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Province Province { get; set; }
        public virtual State State { get; set; }
    }
}
